
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Imanol Fotia
email: imanolfotia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Graphics and general programing tutorials, along with game development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "imanolfotia.com"
twitter_username: ImanolFotia
github_username:  imanolfotia

# Build settings
sass:
  sassdir: _sass
include: ['_pages']
include: ['_pages/Bison-Software']
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: jekyll-theme-time-machine
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
coderay:
  coderay_wrap:              div
  coderay_line_numbers:      inline
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_bold_every:        10
  coderay_css:               main
